# Generated by Django 3.2.9 on 2022-01-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
