# Generated by Django 3.2.9 on 2022-02-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220201_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='written_by',
            new_name='user',
        ),
    ]
