# Generated by Django 3.2.9 on 2022-02-05 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20220203_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='seen_by',
        ),
        migrations.AddField(
            model_name='listing',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
