# Generated by Django 3.2.9 on 2022-02-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20220209_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
