# Generated by Django 3.2.9 on 2022-02-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20220215_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.ManyToManyField(blank=True, related_name='bids', to='auctions.Bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='initial_bid',
            field=models.IntegerField(),
        ),
    ]
